name: ETTU
favicon: null
layout_spectrum: 0
typography_spectrum: 0.08042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#712b39'
    - '#0d0522'
    - '#d56b65'
    - '#ebeae8'
    - '#5b6465'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
